[package]
name = "turn"
version = "0.0.1"
description = "Lodash-inspired Rust utility turning things into something else"
authors = ["Tom Bazarnik <tommywalkie@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/tommywalkie/turn.git"

[dependencies]
